[package]
authors = ["Jagi Natarajan <jagnat4000@gmail.com>"]
name = "daisy_pot"
edition = "2024"
version = "0.1.0"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
micromath = "2.1.0"
critical-section = "1.2"
embassy-stm32 = { version = "0.6.0", features = ["stm32h750ib", "time-driver-tim5", "unstable-pac",], }
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread"], }
embassy-time = { version = "0.5.1", features = ["tick-hz-32_768"], }
embassy-sync = "0.8.0"
static_cell = "2.1"

# cargo build/run
[profile.dev]
# default is opt-level = '0', but that makes very
# verbose machine code
opt-level = 's'
# trade compile speed for slightly better optimisations
codegen-units = 1

# cargo build/run --release
[profile.release]
# default is opt-level = '3', but that makes quite
# verbose machine code
opt-level = 's'
# trade compile speed for slightly better optimisations
codegen-units = 1
# Use Link Time Optimisations to further inline things across crates
lto = 'fat'
# Leave the debug symbols in (default is no debug info)
debug = 2
