#!/usr/bin/env python3
"""Convert a 1 bpp BMP into a Rust source file.

    python3 imgconv.py ~/Pictures/hobbit_hole.bmp -o src/img_hobbit_hole.rs

Emits width/height/stride consts plus one `pub static [u8; N]` of packed rows.

Output format matches the Sharp framebuffer: row-major, `ceil(width / 8)` bytes
per row, top row first, bit 0 of each byte is the LEFTMOST pixel, and a SET bit
is white. BMP stores rows bottom-up with MSB-first bits and a palette that may
list either color at index 0, so all three are normalized here.
"""

import argparse
import os
import re
import struct
import sys

REVERSE = [int(f"{b:08b}"[::-1], 2) for b in range(256)]


def load_bmp(path):
    """Return (width, height, rows) where each row is a list of 0/1 ints, 1 = white."""
    with open(path, "rb") as f:
        data = f.read()

    if data[:2] != b"BM":
        raise SystemExit(f"{path}: not a BMP")

    pixel_offset, = struct.unpack_from("<I", data, 10)
    dib_size, = struct.unpack_from("<I", data, 14)
    if dib_size < 40:
        raise SystemExit(f"{path}: unsupported {dib_size}-byte DIB header")

    width, height, planes, bpp = struct.unpack_from("<iiHH", data, 18)
    compression, = struct.unpack_from("<I", data, 30)
    if bpp != 1 or planes != 1 or compression != 0:
        raise SystemExit(
            f"{path}: need an uncompressed 1 bpp BMP, got {bpp} bpp "
            f"compression {compression}"
        )

    # Positive height means the first row in the file is the BOTTOM of the image.
    bottom_up = height > 0
    height = abs(height)

    # Palette entries are BGRA. Whichever of the two is brighter is the white one.
    pal = data[14 + dib_size:14 + dib_size + 8]
    if len(pal) < 8:
        raise SystemExit(f"{path}: missing 2-entry palette")
    lum = [0.114 * p[0] + 0.587 * p[1] + 0.299 * p[2] for p in (pal[0:3], pal[4:7])]
    white_index = 0 if lum[0] >= lum[1] else 1

    stride = ((width * bpp + 31) // 32) * 4  # BMP rows are padded to 4 bytes
    if len(data) < pixel_offset + stride * height:
        raise SystemExit(f"{path}: truncated pixel data")

    rows = []
    for y in range(height):
        base = pixel_offset + y * stride
        row = data[base:base + stride]
        rows.append([
            1 if ((row[x >> 3] >> (7 - (x & 7))) & 1) == white_index else 0
            for x in range(width)
        ])
    if bottom_up:
        rows.reverse()
    return width, height, rows


def pack(rows, width, invert):
    """Pack rows LSB-first into ceil(width / 8) bytes per row."""
    stride = (width + 7) // 8
    out = bytearray()
    for row in rows:
        line = bytearray(stride)
        for x, px in enumerate(row):
            if px ^ invert:
                line[x >> 3] |= 1 << (x & 7)
        out += line
    return bytes(out)


def preview(rows, width, height, cols=100):
    """Dump the image as ASCII on stderr, block-averaged to fit a terminal.

    Averaging rather than sampling; a dithered image point-sampled at any step
    is just noise.
    """
    ramp = "@%#*+=-:. "  # dark to light
    bw = max(1, (width + cols - 1) // cols)
    bh = bw * 2  # characters are about twice as tall as wide
    for y in range(0, height, bh):
        line = []
        for x in range(0, width, bw):
            block = [rows[j][i]
                     for j in range(y, min(y + bh, height))
                     for i in range(x, min(x + bw, width))]
            line.append(ramp[int(sum(block) / len(block) * (len(ramp) - 1))])
        print("".join(line), file=sys.stderr)


def ident(path):
    name = re.sub(r"[^A-Za-z0-9]+", "_", os.path.splitext(os.path.basename(path))[0])
    return re.sub(r"_+", "_", name).strip("_").upper() or "IMAGE"


def emit(f, src, name, width, height, packed):
    stride = (width + 7) // 8
    print(f"// Generated by imgconv.py from {os.path.basename(src)} -- do not edit.", file=f)
    print(f"// {width}x{height}, 1 bpp, {stride} bytes per row, top row first.", file=f)
    print("// Bit 0 is the leftmost pixel; a set bit is white.", file=f)
    print(file=f)
    print(f"pub const {name}_WIDTH: usize = {width};", file=f)
    print(f"pub const {name}_HEIGHT: usize = {height};", file=f)
    print(f"pub const {name}_STRIDE: usize = {stride};", file=f)
    print(file=f)
    print(f"pub static {name}: [u8; {len(packed)}] = [", file=f)
    for y in range(height):
        row = packed[y * stride:(y + 1) * stride]
        for i in range(0, len(row), 16):
            print("    " + " ".join(f"0x{b:02x}," for b in row[i:i + 16]), file=f)
    print("];", file=f)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("bmp")
    ap.add_argument("-o", "--output", help="write here instead of stdout")
    ap.add_argument("--name", help="Rust identifier (default: from the filename)")
    ap.add_argument("--invert", action="store_true", help="swap black and white")
    ap.add_argument("--preview", action="store_true", help="dump ASCII art on stderr")
    args = ap.parse_args()

    width, height, rows = load_bmp(args.bmp)
    if args.preview:
        preview(rows, width, height)

    packed = pack(rows, width, args.invert)
    name = args.name or ident(args.bmp)

    print(f"{os.path.basename(args.bmp)}: {width}x{height}, {len(packed)} bytes",
          file=sys.stderr)

    if args.output:
        with open(args.output, "w") as f:
            emit(f, args.bmp, name, width, height, packed)
    else:
        emit(sys.stdout, args.bmp, name, width, height, packed)


if __name__ == "__main__":
    main()
